
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 14 17:06:47 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 20;
  public static final int MINUSDECR = 18;
  public static final int CHAR = 41;
  public static final int CONST = 8;
  public static final int NAMESPACE = 5;
  public static final int LPAREN = 36;
  public static final int SEMI = 32;
  public static final int CONTINUE = 10;
  public static final int INT = 40;
  public static final int LESS = 26;
  public static final int MINUS = 16;
  public static final int RPAREN = 37;
  public static final int AND = 29;
  public static final int MOREEQUAL = 27;
  public static final int OR = 30;
  public static final int BOOL = 42;
  public static final int COMMA = 33;
  public static final int EQUALEQUAL = 23;
  public static final int RIGHTSQPAR = 35;
  public static final int DOUBLEDOTS = 14;
  public static final int PLUS = 15;
  public static final int IF = 12;
  public static final int LESEQUAL = 28;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int LEFTSQPAR = 34;
  public static final int EQUAL = 22;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MOD = 21;
  public static final int IDENT = 43;
  public static final int BREAK = 11;
  public static final int VOID = 7;
  public static final int MULTIPLE = 19;
  public static final int COLON = 31;
  public static final int LBRACE = 38;
  public static final int ELSE = 13;
  public static final int READ = 4;
  public static final int RBRACE = 39;
  public static final int PLUSINCR = 17;
  public static final int PROG = 2;
  public static final int DIFF = 24;
  public static final int PRINT = 3;
  public static final int MORE = 25;
}

