
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 29 13:23:27 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 16;
  public static final int MINUSDECR = 14;
  public static final int CHAR = 37;
  public static final int CONST = 8;
  public static final int NAMESPACE = 5;
  public static final int LPAREN = 32;
  public static final int SEMI = 28;
  public static final int INT = 36;
  public static final int LESS = 22;
  public static final int MINUS = 12;
  public static final int RPAREN = 33;
  public static final int AND = 25;
  public static final int MOREEQUAL = 23;
  public static final int OR = 26;
  public static final int BOOL = 38;
  public static final int COMMA = 29;
  public static final int EQUALEQUAL = 19;
  public static final int DOUBLEDOTS = 10;
  public static final int RIGHTSQPAR = 31;
  public static final int PLUS = 11;
  public static final int DOT = 40;
  public static final int LESEQUAL = 24;
  public static final int FINDANY = 41;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int LEFTSQPAR = 30;
  public static final int EQUAL = 18;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MOD = 17;
  public static final int IDENT = 39;
  public static final int VOID = 7;
  public static final int MULTIPLE = 15;
  public static final int COLON = 27;
  public static final int LBRACE = 34;
  public static final int READ = 4;
  public static final int RBRACE = 35;
  public static final int PLUSINCR = 13;
  public static final int PROG = 2;
  public static final int DIFF = 20;
  public static final int PRINT = 3;
  public static final int MORE = 21;
}

