
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 28 15:34:20 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int MINUSDECR = 20;
  public static final int CHAR = 43;
  public static final int CONST = 7;
  public static final int LPAREN = 38;
  public static final int SEMI = 34;
  public static final int CONTINUE = 13;
  public static final int INT = 42;
  public static final int LESS = 28;
  public static final int MINUS = 18;
  public static final int RPAREN = 39;
  public static final int AND = 31;
  public static final int MOREEQUAL = 29;
  public static final int OR = 32;
  public static final int BOOL = 44;
  public static final int COMMA = 35;
  public static final int CLASS = 9;
  public static final int EQUALEQUAL = 25;
  public static final int RIGHTSQPAR = 37;
  public static final int PLUS = 17;
  public static final int IF = 15;
  public static final int LESEQUAL = 30;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int LEFTSQPAR = 36;
  public static final int EQUAL = 24;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MOD = 23;
  public static final int IDENT = 45;
  public static final int BREAK = 14;
  public static final int VOID = 6;
  public static final int MULTIPLE = 21;
  public static final int FOREACH = 12;
  public static final int COLON = 33;
  public static final int LBRACE = 40;
  public static final int ELSE = 16;
  public static final int READ = 4;
  public static final int WHILE = 11;
  public static final int RBRACE = 41;
  public static final int PLUSINCR = 19;
  public static final int EXTENDS = 10;
  public static final int PROG = 2;
  public static final int DIFF = 26;
  public static final int PRINT = 3;
  public static final int MORE = 27;
}

